# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2019-2020 VMware, Inc. All rights reserved.
# Copyright (c) 2016-2019 Carbon Black, Inc. All rights reserved.

name:            KernelEventCollectorModule
build-rules:     ${UTIL_DIR}/build-module.sh
source-version:  ${KERNEL_MAJOR_VERSION}.${KERNEL_MINOR_VERSION}.${KERNEL_PATCH_VERSION}
allow-sub-docker-builds:
builders:
    - redhat6-gcc48-relwithdebinfo

service-env:
    PROJECT_VERSION:     $${SOURCE_VERSION}
    UTIL_DIR:            ${UTIL_DIR}
    JOBS:                1
    BUILD_TYPE:          release
    BUILD_VERBOSE:       no
    BULLSEYE_KEY:

options:
    - module_name=event_collector
    - module_name=cbsensor

conan-replacements:
    KERNEL_API_VERSION: CB_EVENT_API_2_1
    CONAN_UTIL_VERSION: ConanUtil/[~=1.8.x]@${UTIL_CHANNEL}
    CPPUTEST_VERSION: CppUTest/3.8.898+898@${VENDOR_CHANNEL}
    KERNEL_HEADERS_VERSION: # Note, this is needed here for proper dependency tracking
    KERNEL_RHEL_6_6_VERSION: Kernel_2.6.32-504.el6.x86_64/cb-898@re/develop  # 6.6
    KERNEL_RHEL_6_7_VERSION: Kernel_2.6.32-573.el6.x86_64/cb-898@re/develop  # 6.7
    KERNEL_RHEL_6_8_VERSION: Kernel_2.6.32-642.el6.x86_64/cb-898@re/develop  # 6.8
    KERNEL_RHEL_6_9_VERSION: Kernel_2.6.32-696.el6.x86_64/cb-898@re/develop  # 6.9
    KERNEL_RHEL_6_10_VERSION: Kernel_2.6.32-754.el6.x86_64/cb-898@re/develop # 6.10
    KERNEL_RHEL_7_0_VERSION: Kernel_3.10.0-123.el7.x86_64/cb-898@re/develop  # 7.0
    KERNEL_RHEL_7_1_VERSION: Kernel_3.10.0-229.el7.x86_64/cb-898@re/develop  # 7.1
    KERNEL_RHEL_7_2_VERSION: Kernel_3.10.0-327.el7.x86_64/cb-898@re/develop  # 7.2
    KERNEL_RHEL_7_3_VERSION: Kernel_3.10.0-514.el7.x86_64/cb-898@re/develop  # 7.3
    KERNEL_RHEL_7_4_VERSION: Kernel_3.10.0-693.el7.x86_64/cb-898@re/develop  # 7.4
    KERNEL_RHEL_7_5_VERSION: Kernel_3.10.0-862.el7.x86_64/cb-898@re/develop  # 7.5
    KERNEL_RHEL_7_6_VERSION: Kernel_3.10.0-957.el7.x86_64/cb-898@re/develop  # 7.6
    KERNEL_RHEL_7_7_VERSION: Kernel_3.10.0-1062.el7.x86_64/cb-898@re/develop # 7.7
    KERNEL_RHEL_7_8_VERSION: Kernel_3.10.0-1127.el7.x86_64/cb-898@re/develop # 7.8
    KERNEL_RHEL_7_9_VERSION: Kernel_3.10.0-1160.el7.x86_64/cb-898@re/develop # 7.9
    KERNEL_RHEL_8_0_VERSION: Kernel_4.18.0-80.el8.x86_64/cb-898@re/develop  # 8.0

    # Override the kernel versions
    #  This should be a comma seperated list of kernel versions to match.  (This
    #  is a simple match in the string.)
    #  I.e.  "2.6.32-754,3.10.0-957" would build 6.9 and 7.6
    #        "754,957" would build 6.9 and 7.6
    #        "3.10.0" would build all 7.x versions
    #  NOTE: It is ok to inclued kernels from only one platform.
    KERNEL_OVERRIDE_LIST: ""
    BUILD_VERSION:
    PROJECT_VERSION:

env:
    KERNEL_MAJOR_VERSION: 2
    KERNEL_MINOR_VERSION: 2
    KERNEL_PATCH_VERSION: ${BUILD_VERSION}

    UTIL_CHANNEL: ${DEFAULT_CHANNEL}
    VENDOR_CHANNEL: ${DEFAULT_CHANNEL}
    COMMON_CHANNEL: ${DEFAULT_CHANNEL}
    UTIL_DIR: /src/util
