dist: bionic
language: bash

services:
  - docker # Linux tests are run in Docker containers.

addons:
  homebrew:
    brewfile: Brewfile.travis # mac OS dependencies.
    # libsignal-protocol-c is still not in the Travis CI Homebrew snapshot, the
    # line below could be removed when the snapshot has been updated to speed up
    # the OSX job.
    update: true

matrix:
  include:
    - os: linux
      env: BUILD_FLAVOR=tumbleweed
#    - os: linux
#      env: BUILD_FLAVOR=debian
#    - os: linux
#      env: BUILD_FLAVOR=ubuntu
    - os: linux
      env: BUILD_FLAVOR=arch
#    - os: linux
#      env: BUILD_FLAVOR=fedora
    - os: osx
      env:
        # Ensure that "keg-only" Homebrew versions are used.
        - PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig:$PKG_CONFIG_PATH"
        - PKG_CONFIG_PATH="/usr/local/opt/expat/lib/pkgconfig:$PKG_CONFIG_PATH"
        - PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig:$PKG_CONFIG_PATH"
        - PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
        - PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH"
        - PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"

before_install:
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      # Ensure that Travis uses the latest version of Docker.
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      docker build -f Dockerfile."$BUILD_FLAVOR" -t profanity .
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    docker run -it profanity ./ci-build.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    ./ci-build.sh;
    fi

after_failure:
  - cat ./config.log
  - env
